### ISSUE TITLE
CaseClauseError in parse_extensions when :rfc822Name identifier case appears in :crlDistributionPoints list.

### ISSUE THREAD

**Issue by toddholmberg** [CaliDog/EasySSL#9]
```
10:37:59.774 [error] ** (CaseClauseError) no case clause matching: {:rfc822Name, 'Class3SecurityServices_3@crl.comodo.net'}
    (easy_ssl 1.1.2) lib/easy_ssl.ex:400: anonymous fn/1 in EasySSL.parse_extensions/1
    (elixir 1.10.1) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (easy_ssl 1.1.2) lib/easy_ssl.ex:399: anonymous fn/2 in EasySSL.parse_extensions/1
    (elixir 1.10.1) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (easy_ssl 1.1.2) lib/easy_ssl.ex:395: anonymous fn/2 in EasySSL.parse_extensions/1
    (elixir 1.10.1) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (easy_ssl 1.1.2) lib/easy_ssl.ex:70: EasySSL.parse_der/2
    (tls_worker 0.1.0) lib/tls_worker/certificate.ex:140: TLSWorker.Certificate.process_certificate/
```

Here's a possible fix:

```
{:Extension, {2, 5, 29, 31}, _critical, crl_distribution_points} ->
              Map.put(
                extension_map,
                :crlDistributionPoints,
                crl_distribution_points
                |> Enum.reduce([], fn distro_point, output ->
                  case distro_point do
                    {:DistributionPoint, {:fullName, crls}, :asn1_NOVALUE, :asn1_NOVALUE} ->
                      crl_string =
                        crls
                        |> Enum.map(fn identifier ->
                          case identifier do
                            {:uniformResourceIdentifier, uri} ->
                              " URI:#{uri}"
                            {:rfc822Name, identifier} -> " RFC 822 Name: #{identifier}"
                            {:directoryName, _rdn_sequence} ->
                              "" # Just skip this for now, not commonly used.
                          end
                        end)
                        |> Enum.join("\n")

                      output = ["Full Name:" | output]
                      output = [crl_string | output]
                      output
                      |> Enum.reverse()

                    _ ->
                      Logger.error("Unhandled CRL distrobution point #{inspect distro_point}")
                      output
                  end
                end)
                |> Enum.join("\n")
              )
```

I have a pull request in for this issue.

**Comment by Fitblip** [comment]
Also merged! (thanks again!)
